### ISSUE TITLE
Undo re-ordering layers via layer panel results in error and layer panel misrepresentation

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1694]
new default doc, 
select rect tool and draw a shape outside the AB bounds (it will be above the AB in the layers panel), 
in the layers panel drag the Rectangle 1 layer below the AB
cmd/ctrl + z to undo

Result: Rect layer is now still on canvas but not in layers panel and if you click on Layer 1 (the default empty layer), you'll get:
```Action layers.select failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Select” is not currently available.```
and then the layers panel will update.

**Comment by chadrolfs** [comment]
You can also run into 
`Uncaught TypeError: Cannot read property 'id' fo null`
with multiple layers (reorder them, then undo)

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
I no longer get errors but the layers panel still does not update correctly.  related to or the same as #1769 
if same, mark 1769 as dupe and reassign to me.

https://www.dropbox.com/s/w8fi9x6nedjlwew/Undo-LPupdateFail.mov?dl=0

**Comment by mcilroyc** [comment]
Hey @chadrolfs  - it seems to me like *this* bug is fixed.  The remaining visual indented-ness (1769) seems like a separate and UI-related bug.  Even your video linked above seems to correctly show that the behavior described in this bug is fixed (since the repro steps never involved dragging the rect *IN* to the artboard).  Sure, I'm splitting hairs :banana:, but also at the technical level these seem to be distinct from each other.
