### ISSUE TITLE
Command click won't select artboards

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1707]
Neither clicking on the artboard background nor the artboard title selects the artboard. It seems like at least the latter should.

**Comment by chadrolfs** [comment]
I think that is as design.  It's like trying to cmd + click on a group.

**Comment by chadrolfs** [comment]
@iwehrman do you disagree?  ^^

**Comment by placegraphichere** [comment]
CMD+click should always select an artboard (with move tool selected). Current release works that way

**Comment by chadrolfs** [comment]
Current release is wrong tho.  You have to double-click to drill into the AB layer and select it's children and marquee select includes the AB which it shouldn't. 
My argument technically speaking is that AB layers under the hood are essentially group layers and behave similarly.  You can't cmd+click and select a group layer.  If we want to somehow special case ABs in this way, I think it will take up valuable dev time that is needed elsewhere.

**Comment by chadrolfs** [comment]
I see what you mean about cmd+click on the title tho - that's how it works in standard PS

**Comment by placegraphichere** [comment]
yeah, I'm only speaking about the artboard title for this whole thing. CMD+click should probably not select an artboard when clicking on the artboard area. 

This can create a lot of confusion for users, especially when zoomed-in where there may be no off-artboard place to de-select. Otherwise, accidental selecting and repositioning of the artboard can occur when it was probably not wanted. 

title CMD+click = yes
artboard area CMD+click = no

**Comment by chadrolfs** [comment]
works if there are no underlying layers, related to #1751
