### ISSUE TITLE
Errors opening up files created for Character Animator

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1732]
`Failed to build fill for layer <n> Error: Unable to parse Photoshop color object`

**Comment by chadrolfs** [comment]
slack me for test file

**Comment by iwehrman** [comment]
This is not a bug. The "errors" are harmless warning messages related to the fact that the document uses CYMK colors and hence is unsupported. @mcilroyc: do you think we should downgrade those `error` messages to warnings? 

FBNC to @mcilroyc, to decide if he wants to downgrade those messages or just close this bug.

**Comment by mcilroyc** [comment]
It seems like *something* should be done to fail more gracefully in this situation.  I don't think simply downgrading that error is right, since you could imagine other conditions where this failure to parse the color actually IS an error.  @chadrolfs what's your take?  Other than the console error, does everything else function as expected to the end-user?  

Should we attempt to recognize that these are CYMK colors and more gracefully "give up".  Should we try to bail out earlier in the process for Character Animator things?

**Comment by chadrolfs** [comment]
I think we should more gracefully give up like we do with other unsupported docs.  Seeing that much red in the console isn't a "feel good".  Nothing functionally bad happens that I can tell.

**Comment by iwehrman** [comment]
The failure seems perfectly graceful here. There are no unhandled errors, AFAIK. We just print some error messages and then the document is treated as unsupported. We could have a custom error in the case of CMYK colors, but the end result would be the same.

**Comment by mcilroyc** [comment]
Current suggestion: a **warning** message that says "we didn't even try to parse this stroke/fill color because it was not RGB".

After looking more closely at this I'm recanting my earlier position (that we shouldn't downgrade this to a warning) because I now realize it is possible to explicitly recognize that photoshop is specifying a non-RGB color.

Follow-up question: would we ever have an otherwise-supported doc that has a specific shape with a fill color that was specified as CMYK?  Is it OK to just "ignore" CMKY colors while parsing fills/strokes/type into our model?

**Comment by chadrolfs** [comment]
AFAIK color modes are global to the doc; you can't have one layer in rgb and one layer in cmyk or some other color mode.

**Comment by mcilroyc** [comment]
welp, I threw out a quick PR to halt the error parade, and provide a single point of color object validation

**Comment by chadrolfs** [comment]
thanks @mcilroyc

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
