### ISSUE TITLE
Smart guides and direct select overlays are inconsistent

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1734]
Direct (command) select seems to target different layers than are targeted by smart guides, which at least causes a lot of visual noise and at worst is really frustrating. To reproduce, open the VermillionArtboards.PSD file and try to directly target just about any object on any artboard, e.g., the seated woman in the top-left corner of the document.

It's not clear to me why we need two different overlays. If there's a good reason to have them both, it would be nice to make sure they're both implemented to the same specification so that they're consistent.

**Comment by iwehrman** [comment]
CC @volfied.

**Comment by volfied** [comment]
We need to discuss this, because I'm not sure what to do exactly. 

@placegraphichere: If we're always going to have smart guides on in Photoshop, what I think we should do is, disable cmd+ highlight for superselect (but still have it work), and match group highlighting to the same magenta color. 

This way, users will see the pop up ruler values (distance between selected layer and hovered layer) only when cmd key is down, and in other itmes, they'll see our same color highlight graphic.

**Comment by volfied** [comment]
Keep in mind we can set the smart guide color to anything we want.

**Comment by iwehrman** [comment]
I agree we should not have both at the same time, and that they should be styled consistently. (Conceivably though, if the user has disabled smart guides then perhaps they also don't want the hover highlighting?)

A separate issue though is the difference in algorithms used for highlighting. If we have one algorithm for highlighting with smart guides enabled and another one when they're disabled, it seems like the objects highlighted should still be the same in the same contexts.

**Comment by volfied** [comment]
I do not see the inconsistency, can you provide a screenshot? Or better, a small file where I can easily repro?

**Comment by iwehrman** [comment]
I can't provide a screenshot because smart guides. The repro steps in the original comment are the best I can do. It may be related to #1760.

**Comment by designedbyscience** [comment]
![vermilionartboards_psd___66_7___desktop__rgb_8_____and_slack_and__1__playground_js___trello_and_issues_ _adobe-photoshop_spaces-design](https://cloud.githubusercontent.com/assets/22372/8780118/dfaa5a0e-2ed4-11e5-8330-0ffcfd888842.png)

**Comment by designedbyscience** [comment]
Right now I think we'd have a problem if we simply turned off our overlay if smart guides is on as, like @iwehrman mentioned, I definitely see the case where an object appears active in smart guides but if you click you select a different object

**Comment by volfied** [comment]
Yeah, it's the invisible layers. Smart guides work on pixel data, we work on bound data.

**Comment by placegraphichere** [comment]
I was sure something would come up as we moved to Ps transform... and it finally has arrived! 

I think @volfied's suggestion sounds appropriate.

@iwehrman I wonder if we can in the future get highlighting and smart guides under one umbrella? Maybe as part of some bug work that should happen?

**Comment by volfied** [comment]
Not unless we implement superselect in core. It has no concept of groups/ layer hierarchy. And on our side we have no concept of invisible layers, so we get bugs like the one Eric posted above.

At least for that bug, I may be able to work something out on Core side to send us which layer is being highlighted by the smart guides and we select it, instead of what we think should be selected. That might find a sweet spot in the middle.

**Comment by iwehrman** [comment]
After October, implementing our selection model in core is sounding like a better and better idea.

**Comment by iwehrman** [comment]
Also, I guess this is obvious, but: the problem with @volfied's suggestion is that cmd-select-hover will highlight different layers depending on whether or not smart guides are enabled, which is darn confusing.

**Comment by chadrolfs** [comment]
@iwehrman and @designedbyscience say it seems to be working correctly
