### ISSUE TITLE
Errors accessing color picker after creating Type or shape

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1738]
cmd/ctlr + n
select type tool
click on canvas and type, hit Enter (numpad) or Esc to commit
click on Type Color picker.
Result: `Action dialog.openDialog failed: TypeError: undefined is not a function`
`Action shortcuts.removeShortcut failed: Error: Unknown policy ID: 14`

2nd attempt succeeds

**Comment by chadrolfs** [comment]
cmd/ctlr + n
drag out a rect shape within AB
click on Color picker for Stroke
BOOM

**Comment by volfied** [comment]
This doesn't go boom anymore!

**Comment by chadrolfs** [comment]
I made it go boom:
cmd/ctlr + n
select type tool
click on canvas and type, hit Enter (numpad) or Esc to commit
click on Type Color picker and set a color
hit enter or click on color picker to close
repeat steps above:
2nd attempt fails

**Comment by chadrolfs** [comment]
![screen shot 2015-07-20 at 2 21 45 pm](https://cloud.githubusercontent.com/assets/8442631/8787883/79f20312-2eeb-11e5-8ccc-3e59cd0f0c37.png)

**Comment by volfied** [comment]
This one is baffling me, but mostly because I don't know much about Dialogs.

@designedbyscience , I'll give this to you. Problem is two fold - if I create a new document, switch to type tool, type something, press esc to commit, and then click the Type color picker square (with the Aa), `setState({target: ...})` gets called, but also the dialog store emits a change event, and causes a re-render where _positionDialog gets an error. 

Other problem is, if target is defined, it still causes the problem above, because `this.state.target.offsetParent` is null in some cases.

**Comment by designedbyscience** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent: offsetParent returns null when the element has style.display set to "none"
