### ISSUE TITLE
Undo failure: drag and drop nested group

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1843]
`Action edit.undo failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Select” is not currently available.`

https://www.dropbox.com/s/znpizclvk9z7wdk/Undo-Fail.mov?dl=0

**Comment by chadrolfs** [comment]
occurs in prerelease build m.177 as well as current pg-dev.412 and master @ 6a2880c

**Comment by iwehrman** [comment]
Actually, this might be for @mcilroyc instead.

**Comment by chadrolfs** [comment]
this may or may not be a prerelease blocker.  doesn't seem like anything bad happens afterwards.  thoughts?

**Comment by mcilroyc** [comment]
@chadrolfs : good news and bad news.  The good news is that I think this is easily addressed by the above noted PR (still open as of right now).  The *bad* news is that this issue is much worse than indicated by the title of the issue.  I think ALL layer reordering is busted (vis a vis history) in that undo doesn't actually work on the first try (it just changes the selection state).
