### ISSUE TITLE
shortcut modifier to zoom doesn't work with Select tool

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1844]
open a file, hold down cmd/ctrl + space + click and drag

Result: cursor changes to magnifying glass but performs marquee select (works with other tools)

**Comment by volfied** [comment]
While trying to reproduce the problem, I've noticed that cmd+space on Mac causes Spotlight to pop up, preventing us from receiving a key down event for space bar. If you hold space then cmd, scrubby zoom works fine.

Since we rely on key events coming from PS for this, we should see if this is a simple fix on the core side.

**Comment by chadrolfs** [comment]
We decided in stand-up this morning that this is now desired behavior, right?

**Comment by volfied** [comment]
Yes, however, reason it doesn't work in select tool is because we're
stealing mouse down events... So while it presents correct behavior, it's
not the solution.

Therefore I'm not sure if this is an issue... we're going to disable the
scrubby zoom.

**Comment by volfied** [comment]
I've disabled scrubby zoom in pgdv, space+cmd / space+option do nothing now.

**Comment by chadrolfs** [comment]
I guess that's one way of fixing it.

**Comment by volfied** [comment]
Re-opening this. @chadrolfs I've reverted my change and scrubby zoom is back. 

Please refer to this techdoc from 10 years ago for the possible fixes.

If it's still performance wise bad, please let us know and Jesper will look into it.

http://www.adobe.com/support/techdocs/331723.html
