### ISSUE TITLE
Text Edit: Shortcut to Hide results in standard dialog that doesn't honor choice to hide extras

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1879]
while in text edit mode, cmd/ctrl + h

Result: 
![screen shot 2015-07-31 at 10 20 37 am](https://cloud.githubusercontent.com/assets/8442631/9012970/d40b792a-376d-11e5-91e8-61c57092170f.png)

Click [Hide Extras]
Result: Hide Photoshop is executed.

**Comment by chadrolfs** [comment]
we just need to suppress the dialog here?  core bug?

**Comment by chadrolfs** [comment]
What should our default choice be?

**Comment by placegraphichere** [comment]
I don't think we should use this. We are moving keyboard shortcuts to a more streamlined workflows. So supporting older legacy shortcuts should not be our concern.

CMD+h should follow the OS standard to hide the app. Preferably, if text being edited, that text should exit text editing mode and the application should hide. 

If that's not possible, then when in text edit mode, the command should simply be ignored until the user finishes editing and exits text edit mode on their own.

**Comment by iwehrman** [comment]
@chadrolfs This requires a Watson issue. Please ask that this dialog be suppressed and that the "Hide Photoshop" option be chosen as the default. Back to @chadrolfs for Watsoning.

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4051688

**Comment by jsbache** [comment]
BTW: Here is what I see.
In Designshop + modal text tool active. You press command-H..
When you answer "show extras", then Photoshop takes the normal menu command route (if you answer no, it hides immediately).
In this case we send the menu command 3500 to javascript.
Javascript turns around and issues performMenucommand(7001). 7001 is "hide Photoshop". In this case js should have issued: performMenuCommand(3509).
If we want to always hide Photoshop, then we can rig Photoshop, Otherwise js needs to become more clever (probably adapting a strategy such as "if js receives 3500 during text edit, then it is a hide extra request").

**Comment by jsbache** [comment]
Fixed in staging with CL: 1040986. The tricky part is that since we suppress the dialog, we need to ensure that we do not update the PS preferences for classic. The change therefore hides PS immediately (and then simulates a cancel for the dialog). This means that in standard, you will see the dialog when you press command-H for the first time

**Comment by tiburbage** [comment]
Closing. On Mac in Design Space, the behavior is to minimize the app regardless of the user preference for this shortcut.
