### ISSUE TITLE
Make sure tools are available (new customize toolbar in standard PS)

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1897]
With customized toolbar feature in, tools may or may not be available.

**Comment by chadrolfs** [comment]
There will need to be work on both js and core sides.

**Comment by chadrolfs** [comment]
@ktaki please file watson

**Comment by ktaki** [comment]
https://watsonexp.corp.adobe.com/#bug=4030512

**Comment by chadrolfs** [comment]
Here is the result of not having tools available:
![screen shot 2015-08-05 at 2 23 01 pm](https://cloud.githubusercontent.com/assets/8442631/9098246/728deaf2-3b7d-11e5-81ff-af9421552cb3.png)

**Comment by chadrolfs** [comment]
Not fixed with current master 3ba5be8 and pg-dev.446

![screen shot 2015-08-12 at 3 30 18 pm](https://cloud.githubusercontent.com/assets/8442631/9238415/f44c6cba-4106-11e5-89e7-23660b4aed1c.png)

**Comment by chadrolfs** [comment]
@iwehrman fitz is working on the core side of this bug but we need better error handling for cases like this so that when DS fails, users get kicked back into standard instead of hung in DS.

**Comment by iwehrman** [comment]
This should be fixed in core as of Mac pgdev 470.

On the JS side, the failure is only thorough if the default (select) tool can't be activated. I think we're not wrong to consider that to be a catastrophic failure, and the controller correctly returns the user to standard PS with the "unrecoverable error" message as designed. I think you aren't getting kicked back to standard because that only happens when the JS sources are compiled.

**Comment by chadrolfs** [comment]
Thanks @iwehrman. Testing that out now.

**Comment by chadrolfs** [comment]
Yep, looks fixed.

**Comment by ktaki** [comment]
Yes, it's working now.
