### ISSUE TITLE
Search: Paste into field repeats twice

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1906]
Copy some text ctrl + c, "designspace"
ctrl + f to bring up Search
click in field and hit ctrl + v to paste

Result: "designspacedesignspace"

**Comment by volfied** [comment]
@iwehrman This is likely same reason as #1907, maybe we don't need all the fancy logic on Windows, and let the OS calls do their work?

**Comment by volfied** [comment]
We are getting two keydown events for v when control is down.

**Comment by volfied** [comment]
https://watsonexp.corp.adobe.com/#bug=4051877

**Comment by tiburbage** [comment]
Watson xref: https://watsonexp.corp.adobe.com/#bug=4051877

I think we have demonstrated that Spaces in a more generic context (our interactive test app) is neither sending repeat keydowns nor repeating ClipboardEvent "paste" events. We're seeing a normal KeyboardEvent for 'v' with modifier (Command or Control), and a single ClipboardEvent "paste" event, and only a single instance of the text copied to the clipboard is being pasted to a text input element.

**Comment by volfied** [comment]
Problem: On Windows, <input> element handles the ctrl+v paste event, and PS is also sending us a second paste command, which turns into edit.paste action, which we use to synthesize a window.paste event. Hence the double paste.

Former event does not happen in Mac, cmd+v does not get handled by the <input> and we get only one paste event from plugin which turns into edit.paste action.

**Comment by tiburbage** [comment]
Using pgdev.709 (playground-dev @1046519), the use cases: paste to Find text input field, paste into name field of a layer WORK (no double paste). However, I still see doubled text when pasting into Text Tool text. That's either on initial mousedown after invoking the tool OR subsequently editing an already created text layer text. John requested the Watson bug be set back to ToFix rather than treating the Text input as a separate bug.

**Comment by iwehrman** [comment]
All these cases seem fixed to me. FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
YAY!
