### ISSUE TITLE
Add Super Search to keyboard shortcut list

### ISSUE THREAD

**Issue by joelrbrandt** [adobe-photoshop/spaces-design#1929]
the "Help > Keyboard Shortcuts" menu lists keyboard shortcuts. But, Super Search isn't in the list! :scream:

**Comment by joelrbrandt** [comment]
Actually, I guess it's under the "Layers" menu, so maybe it doesn't belong in the keyboard shortcuts? Maybe @placegraphichere or @iwehrman has an opinion? This feature has gotten so much bigger than just layers...

**Comment by iwehrman** [comment]
I agree that the `Layers` menu probably is no longer the right place for it. Actually we should still have a `Find Layers` entry under `Layers`, which will trigger @designedbyscience's in-panel layers-only search feature. We should have an `App Search` menu entry elsewhere; possibly under `Edit`?

So far we've only put non-menu keyboard shortcuts in that dialog. But I agree that it is important enough to jam it in there anyway.

**Comment by hamburge** [comment]
Putting it under `Window` makes more sense to me than `Edit`

**Comment by iwehrman** [comment]
This is now in the keyboard shortcuts dialog, and the search menu command has been moved under `Edit`. The placement in the keyboard shortcuts dialog is a little weird, but that doesn't matter because we'll have to spruce that whole dialog up before M3 anyway. Closing this out since @joelrbrandt is busy with other things.
