### ISSUE TITLE
Type tool deselect should not call resetLayers

### ISSUE THREAD

**Issue by volfied** [adobe-photoshop/spaces-design#1936]
If there is extra core work that needs to be done to prevent calling reset on type tool deselect, than please track it with a Watson bug.

**Comment by pineapplespatula** [comment]
has watson bug 4032729

**Comment by iwehrman** [comment]
@pineapplespatula sez:

    when you exit the modal state, our model has be modified to reflect the current modal selection. When
    you escape without reseting we dont refelct the whole layer state. so we wont update to a mixed 
    selection in the property panel

**Comment by iwehrman** [comment]
I think this can be deferred until after M3.

**Comment by iwehrman** [comment]
After re-reading my comment on the above Watson bug, I now think I was confused previously about the nature of this bug. I thought it was about the fact that we call `resetLayers` after editing a type layer. (Which, if that's even a bug, it's a rather benign one.) But I now realize it's actually about the `resetLayers` call on deselect of the type tool. I have no idea why we're doing that, especially since we get a `set` or `make` event whenever a text layer is committed or created, and that calls `resetLayers`. The condition under which we call it also doesn't make much sense. So, I'm just going to rip it out unless somebody objects so that we can close this bug.

**Comment by iwehrman** [comment]
Wait, maybe this was supposed to handle the case in which you _cancel_ a modal edit? But switching tools should commit the current modal state, not cancel it AFAIK. This might make sense in the case of the superselect type sub-tool, for which deselection and exiting the modal state should be co-occurring, but it ain't there. Also, canceling out of the type subtool seems to incorrectly leave you in the type tool anyway...
