### ISSUE TITLE
Consider adding slight translucency to UI

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1978]
I still kind of miss the slight translucency that we used to have in the non-dialog parts of the UI. I think this might improve visibility into a bigger part of the canvas:
![opaque](https://s3.amazonaws.com/f.cl.ly/items/2d0i1P1O143z1i1a0g2O/Image%202015-08-10%20at%205.46.00%20PM.png)

Incidentally, adding some slight translucency might also help with #1976.

**Comment by DivyaPrabhakar** [comment]
A couple opinions about this: 

- I asked Charles Pearson about whether taking away the translucency was part of user feedback or branding necessity -- the answer is no for both questions, taking away the translucency was just something that happened over time by accident and no one commented either way. 

- In focus groups held last summer, some said it gave the perception of depth and space, traits we are presumably aiming for in Design Space, especially in contrast to classic Photoshop UI. It also may be worth a try now because the properties panel is thicker than the initial designs (drafted last summer), so the idea of more space could be useful.

**Comment by iwehrman** [comment]
Welp, I guess I got out-voted on this one. I shall return!
