### ISSUE TITLE
Secondary search info is hard to read

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1992]
The contrast is low, there isn't a lot of space between the primary and secondary info, and it's relatively tiny. 

![image](https://cloud.githubusercontent.com/assets/1075154/9211903/d73b9f4c-4039-11e5-8288-ad7609f8e66a.png)

**Comment by placegraphichere** [comment]
Primary 
* color #e6e6e6 
* font-size:1.4rem (14px)

Secondary 
* color #7b7b7b
* font-size: 1.1rem (11px)

Highlight 
* color #2d8ceb

**Comment by chadrolfs** [comment]
@DivyaPrabhakar coordinate with @iwehrman & @placegraphichere

**Comment by DivyaPrabhakar** [comment]
@iwehrman @placegraphichere I got Seth's branch https://github.com/adobe-photoshop/spaces-design/tree/sewalker/search-tweaks and looked at the changes. I agree it an improvement and definitely fixes the contrast issue between varying levels of information in the search tool. I think the color differences Seth made are subtle, noticeable, and clear. My three remaining ideas about search are: 

1. Make the height of each list item in the search feature taller, giving more space to each one. We can change the font size too if we deem appropriate but I think the more vertical space itself allows it to breathe more. We already have scroll enabled so it makes little difference. In addition, the user types queries so quickly, the extra scrolling is negligible. 

![alt text](https://www.dropbox.com/s/8gqlmg3psuu6s6e/Screen%20Shot%202015-08-21%20at%202.23.30%20PM.png?raw=1 "Current state")

![alt text](https://www.dropbox.com/s/qs5ul9ebhenmmgq/Screen%20Shot%202015-08-21%20at%202.23.20%20PM.png?raw=1 "Proposed state with heightened list items")

2. Increase the space a bit between Primary and Secondary info still, since the difference in font size is not too drastic and the color is muted (rightfully so) so adding some space would further indicate they are two different but related bits of information. 

3. I think the text color, the autocomplete color, and the cursor are crowded all together. Maybe we can lessen the opacity on the autocomplete text or darken the color? 

![alt text](https://www.dropbox.com/s/86yroet2ouhdpo0/Screenshot%202015-08-21%2014.57.38.png?raw=1 "Current state")

![alt text](https://www.dropbox.com/s/sscxvo3esqupvip/Screenshot%202015-08-21%2014.58.34.png?raw=1 "Proposed state (lowered opacity")

**Comment by placegraphichere** [comment]
these sound like wonderful additions. For:
A) we are on a 8px grid. So for rems, anything 1.8, 2.4, 3.2 would be great for size.
B) I think we're doing 4 spaces. Not sure what the right amount needs to be. It'd also be interesting to right-align the secondary info, but I don't think that's a matter for this issue. And may take more noodling than this issue requires.
C)  Finding a nice autocomplete color should be easier with the new colors.less.

**Comment by DivyaPrabhakar** [comment]
@placegraphichere just put in a PR with all the changes needed for this issue to be solved When it gets reviewed and merged, he can close it or send it back to Ian to close.

**Comment by iwehrman** [comment]
Fixed by #2221. Nice work @placegraphichere and @DivyaPrabhakar!

**Comment by iwehrman** [comment]
![top gun](http://c2.thejournal.ie/media/2014/05/high-five-5.gif)
