### ISSUE TITLE
Text Transform: When setting font size for a transformed text layer, the size shows a wrong value

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2028]
Create a type layer with 100 pt text.
Transform it to 200 pt.
Select the layer and set the point size to 100 pt in the type panel.
Click on the text layer on canvas to go into the editing mode.
The size now shows 50 pt while its actual size is 100 pt.

**Comment by iwehrman** [comment]
[Watson 4037298](https://watsonexp.corp.adobe.com/#bug=4037298) is the blocking issue. In summary, use the `impliedFontSize` instead of the raw font `size` in the UI, but to make this work in the modal type tool state, the `updateTextProperties` event must also include `impliedFontSize` instead of just the raw size.

Assigning this to @pineapplespatula for now, but feel free to hand it back to me once the core issue is resolved.

**Comment by pineapplespatula** [comment]
Perforce CL 1036188 has the fix for this issue

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
