### ISSUE TITLE
SHIFT-clicking to add to a selection within the selection bounding box fails

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2069]
- Create 4 rects in a 2x2 grid
- Attempt to select all 4 rects
- The final rect will not select since the bounding box of the current selection overlaps 

GIF shows selecting rects individually, then tries to multi-select them

![multi-selection-bounding-interference](https://cloud.githubusercontent.com/assets/3229167/9291677/566a8d94-4393-11e5-8120-27653026ee30.gif)

**Comment by iwehrman** [comment]
@DivyaPrabhakar to narrow down the problem.

**Comment by DivyaPrabhakar** [comment]
EOD Friday, August 21 update

Our policy events are propagating correctly on click or SHIFT + CMD + click. In both of those cases, the selection tool works perfectly no matter where on the layer you click.'

It gets messed up within the red bounding box when only SHIFT + click are pressed. For some reason, the SHIFT only is not propagating events correctly (I don't want to say it nullifies it because we are registering the click in the browser, but it does not call the click function, virtually making the area within the red bounds the Bermuda triangle when SHIFT is held down.) My theory is that the policy action is changing when SHIFT is pressed down and maybe changing to ALPHA_PROPAGATE or something other than NEVER_PROPAGATE which is messing with selection. 

Further investigation on Monday. Need to ask @volfied a list of questions I have generated after looking into this (Don't tell me the answer just yet Barkin, I want to figure this one out myself :)) 

What is happening now when you have SHIFT pressed down and you click INSIDE the red box: 
![alt text](https://www.dropbox.com/s/gyd1qwrapyij07z/not_working_select.gif?raw=1 "Inside + shift")

What is happening now when you have SHIFT pressed down and you click OUTSIDE the red box: 
![alt text](https://www.dropbox.com/s/s996ce91jzuuiqu/working_select.gif?raw=1 "Inside + shift")

**Comment by iwehrman** [comment]
![gifs](http://cdn.meme.am/instances2/500x/1502228.jpg)

**Comment by volfied** [comment]
@DivyaPrabhakar You've figured it out already... but I'll answer any and all questions you have!

**Comment by volfied** [comment]
Over to @chadrolfs to confirm!
