### ISSUE TITLE
SuperSelect: showing blue bounding of images not on targeted AB

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2112]
There might be some edge case around this that should work as is today but if you have two AB - and you have AB 1 selected and as you mouse through, it will in fact show the bounding edge of an image that is in AB2 (that happens to overlap - not visibly - with AB1). Too many distracting bounding boxes appearing and disappearing that aren't relevant to the task at hand.

(I have a video if this does't make sense)

**Comment by placegraphichere** [comment]
is this part of the "don't show hidden layer" issue @iwehrman ?

**Comment by iwehrman** [comment]
Hopefully not, because that is fixed.

**Comment by iwehrman** [comment]
@zoranagee please post a link to the video and, ideally, also a link to the PSD if you/Adobe own the rights to it. Otherwise, just send links via email internally.

**Comment by volfied** [comment]
Can you post the video @zoranagee ?

**Comment by zoranagee** [comment]
The file is up on my transfer on smb://sjshare.corp.adobe.com/Photoshop/ under "DesignSpace"

**Comment by iwehrman** [comment]
Bumping this to high priority because it really makes demoing hard. Oh, and did I mention I need to demo to the big boss this week? :grimacing:

**Comment by volfied** [comment]
@chadrolfs To reproduce this bug, create two artboards (make sure artboard 2 is higher than artboard 1 in the layers panel), put a BIG rectangle in artboard 2, that also overlaps artboard 1.
Then put a small rectangle in artboard 1, and try to highlight it, big rectangle in artboard 2 will steal the highlight, after this fix, it will not highlight because we're not hovering over it in it's own artboard.
