### ISSUE TITLE
Series of errors resulted by creating and moving horizontal guides

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2171]
Create a few horizontal guide at the top or bottom. Try moving them to the center. Cannot recover from the errors.

Action guides.setGuide failed: TypeError: Cannot read property 'orientation' of undefined
Uncaught TypeError: Cannot read property 'orientation' of undefined
Action tools.beforeStartup failed: Error: Unknown policy ID: 4
Uncaught TypeError: Cannot read property 'left' of null
Action export.onReset failed: TypeError: Cannot read property 'close' of null

**Comment by volfied** [comment]
When you create them, are you just clicking in the area, or are you dragging them to the center after creation? 

At what point does the error happen? Is it after creating bunch of them, and the first move, or after couple moves? 

I need more details, and it would help a lot more if you posted the whole log instead of just the collected error lines.

**Comment by ktaki** [comment]
It seems that the errors happen when clicking in the blue highlighted area at the top or bottom, and then try to move a guide created in the area on to the artboard. I will send a error log via email.

**Comment by ktaki** [comment]
@volfied Can you look at this next? This is reproducible so often and consider to be a blocker since DS needs to be reset after the errors. Thanks.

**Comment by volfied** [comment]
@ktaki Issue is addressed in #2217 yesterday, as soon as it's merged, you can test it.

**Comment by ktaki** [comment]
This is fixed. Thanks!
