### ISSUE TITLE
Selecting empty space in AB doesn't target it

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2238]
Create an AB - select in the middle of it (nothing there) - AB becomes deselected. I would expect us to know that I am targeting the AB even though there are no pixels in it.

PS standard works as expected.

**Comment by chadrolfs** [comment]
I believe this was intentionally designed this way so that you can easily select sub-layers directly without having to double-click to drill into the AB. @placegraphichere @volfied Correct?

**Comment by volfied** [comment]
Yes, we do not allow artboard to be selected by clicking on an empty pixel in it. This is due to fact that if the user is zoomed in doing pixel work, and click outside to deselect, they don't get surprised by their selection dropping to the artboard (instead of deselectAll which is what they expect).

**Comment by zoranagee** [comment]
well - I understand that selecting outside of the AB not selecting anything but when you actually select in an AB - you mean to target that area. In standard, if we have auto select layer checked (or actually in any state) it always at least targets that AB. Why would we differ from standard here? With SuperSelect, shouldn't AB essentially be the backmost layer? Thanks
