### ISSUE TITLE
Discoverability: asset links/icons for delete, send link, view on website

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2308]
This needs some XD input.  Currently, you have to click below or above the asset name field which isn't terribly intuitive or discoverable.

**Comment by davealonzo** [comment]
Clicking on the Library name area to select the item doesn't seem to respond. But if you click slightly above or below the name within the hover area, it easily selects as expected. This might be contributing to the issue.

The expected behavior is to click anywhere in the hover area (including the name or thumbnail) to select the item and subsequently invoke the icons.

**Comment by iwehrman** [comment]
XD input received! Back over to @shaoshing.

**Comment by chadrolfs** [comment]
Great!  Simply I think that means this: single click = show icons, double-click = rename
