### ISSUE TITLE
Select hover shows incorrect hit-test

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2370]
- Create shape or text with holes
- hover over the layer
- blue hover shows up
- hover over hole area within the blue bounding box
- click to select
- layer behind will be selected
![select-hit-test-issue](https://cloud.githubusercontent.com/assets/3229167/9753461/c8ddd032-5682-11e5-8d0d-08c6b68ef87d.gif)

**Comment by placegraphichere** [comment]
![select-hit-test-issue-2](https://cloud.githubusercontent.com/assets/3229167/9753498/653df40c-5683-11e5-8f00-036cba3d3c9e.gif)

**Comment by iwehrman** [comment]
I bet @volfied wants to look into this!

**Comment by volfied** [comment]
This is a technical limitation of our own bounds checking and hitTest being asynchronous. It's a problem we've been aware of since first implementation. I'm not sure what we can do to fix it, we had a whole different slew of bugs and usability issues when we turned off hitTest and relied solely on our own bounds (whatever is highlighted will be selected)

Short of getting a pixel map from PS every time for the topmost layer ID at a pixel, I don't see a solution to this. I'll try hooking up hitTest to highlighting so with a slight delay we highlight the layer that'll be selected, but I have my doubts on how that'll look.

**Comment by mcilroyc** [comment]
@placegraphichere check master to see if this is working the way you'd expect.

**Comment by mcilroyc** [comment]
also heads up @chadrolfs and @ktaki - this is a moderatly significant change to the way hover-highlighting works in super-select tool

**Comment by chadrolfs** [comment]
This works now as I would expect but introduced another issue.
