### ISSUE TITLE
Panning lags in DS

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2383]
Open Mt.Hood_Z found in sjshare/Photoshop/Transfer/Zorana/DesignSpaceBugs
Use 2-fingers to pan the file
Release
RESULT: takes time for canvas to 'catch up'
EXPECT: similar canvas panning time to that of PS

(Jesper verified that the lag time is slower in DS)

**Comment by volfied** [comment]
Jesper is working on the scroll/zoom events on core side, where he will send us a "scrollFInished" type of event where we will know to redraw the overlay. We will need to remove our own debouncing of scroll events when this happens.

**Comment by volfied** [comment]
Jesper told me this is likely not going to happen before Oct 1st. So I'm leaving this note here for whoever wants to fix this:

Right now, in actions/ui.js we add a `"scroll"` event listener that calls `setTransformDebounced`, which means we grab all the scroll events, and as long as we receive them, we delay processing the transform. 

However, when Jesper makes the change, so we only get two events (one for beginning, one for end), we'll need to listen to the finished event, and get rid of our own debounced call. Because otherwise, our debounce would fire for the first scroll event, and show the overlay in the wrong place when applicable.

So the solution will be to hide overlays on scroll started event, and call setTransform / re-show overlays on the last scroll finished event.

**Comment by iwehrman** [comment]
Re-assigning to @chadrolfs to file a Watson bug for this work that @jsbache has planned. The goal of the Watson bug is to make it possible for me to know when this work is done so I can make the necessary changes after @volfied skips town, and to help @jsbache to not forget about it for 16.1.

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4066264

**Comment by tiburbage** [comment]
We've closed the Watson issue:
Tested with our latest builds and DS with the cited .psd on both Mac and Windows, comparing standard UI and DS, and see no noticable difference in pan performance.
