### ISSUE TITLE
It should be possible to switch between color formats in the color picker

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2423]
This could make use of the `Menu` component that @designedbyscience is working on, or it could use a split-button widget as in Brackets:
![button](https://s3.amazonaws.com/f.cl.ly/items/0S0o3r3U00332V2F330x/Image%202015-09-11%20at%203.50.00%20PM.png)

 (This is a feature request, but I'm filing it here so it isn't forgotten.)

**Comment by placegraphichere** [comment]
I can imagine a wonderful switcher similar to this example that allows for the switching. Placed either to the left or right of the color input. This was in the original designs for the picker, but was dropped due to scope.

![screen shot 2015-09-14 at 11 24 27 pm](https://cloud.githubusercontent.com/assets/3229167/9867875/d0a32d76-5b37-11e5-8db8-ae696d2d294e.png)

**Comment by chadrolfs** [comment]
reviewed - not M3

**Comment by chadrolfs** [comment]
use arrow keys (fixed)
