### ISSUE TITLE
ALT+drag to duplicate multiple objects does not update layers panel

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2504]
- Select multiple objects
- ALT+drag to duplicate them
- Layers panel will only show one layer selected
- Canvas continues to show multiple layers selected

expected: layers panel should show all layers selected

**Comment by shaoshing** [comment]
The cause is at https://github.com/adobe-photoshop/spaces-design/commit/4729d94cd3309c9756ff1d7b9164192f838325a6#diff-cad1f13dd4227353281fce9ef1e32a58R690 Changing line 690 to `isNewSelected = selected` will fix the problem but I think there must be a reason for adding `i + 1 === layerIDs.length`. Summoning @mcilroyc since he is the author of the commit.

**Comment by placegraphichere** [comment]
fixed
