### ISSUE TITLE
Export panel says "No exports configured" when multiple layers are selected and no matching assets are found

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2574]
Add two shape layers. Add an asset .png to one layer, and add an asset .svg to another. Select both layers in layers panel. The panel says "No exports configured."

**Comment by mcilroyc** [comment]
@placegraphichere this is a bug version of the card we have here to improve mixed state export.  https://trello.com/c/HMUwwcfe

In a nutshell, we don't have a visual representation of multiple selections with totally non-intersecting asset configurations.  Maybe you'll have an idea for a "quick fix" for this?

**Comment by chadrolfs** [comment]
@placegraphichere do you have an interface solution for this?

**Comment by placegraphichere** [comment]
We could add an additional message for this scenario in ExportPanel.jsx at line 192 where we can check for multiple assets with mismatched exports and give a new string warning under something like: EXPORT.EXPORT_MIXED = "Selection has mixed export settings".

**Comment by mcilroyc** [comment]
@placegraphichere I did the thing you suggested.  It's in a branch here if you want to check it out.  `mcilroy/mixed-export-message`.  
https://github.com/adobe-photoshop/spaces-design/compare/mcilroy/mixed-export-message?expand=1

I guess the next step would be to give the user an indication in the case where there are some common assets AND some non-common assets.  Right now the message will only appear if there are only non-common assets. Too crowded otherwise, ya?  This branch is at least a step in the right direction.

**Comment by placegraphichere** [comment]
see #2692

**Comment by mcilroyc** [comment]
@ktaki as of the above-referenced PR, we now display a more nuanced message in the situation you described.

**Comment by ktaki** [comment]
Now it displays "Selection has mixed exports"
