### ISSUE TITLE
X and Y coordinates for a selected layer are w.r.t canvas, not the artboard

### ISSUE THREAD

**Issue by DivyaPrabhakar** [adobe-photoshop/spaces-design#2613]
If the selected shape is on an artboard, the X and Y coordinates should be in relation to the artboard. 

Repro: 

1. Create two artboards, AB1 and AB2
2. Create a shape layer and place it on AB2 in the top left corner
3. X Y coordinates read X: (some non-zero value), Y: 0. 

Expected behavior is  X: 0     Y: 0

**Comment by iwehrman** [comment]
Over to @chadrolfs for verification.

**Comment by chadrolfs** [comment]
Hmmm, well I'm not totally sure it's fixed.  There are some confusing things.  Watch this:
1st: X/Y of AB is 850, 0.  While dragging, you can hold down Space to reposition and as you do, you get the coords according to what the AB is (850/0) but once you let go and stop drawing the rect, the coords change to -1/0 (which is what you're going for with this fix).  So I guess expected behavior is correct after you've finished drawing but not during.

https://www.dropbox.com/s/u6lgdikrv378mxr/XY-Coords.mov?dl=0

Once you are outside the AB, things get very interesting tho.
Trying to set a shape outside AB to 0/0 will always move it to the left and up and reset it to 1024.  Not sure I understand that.

Anyway, based on the video and what I've explained, if the fix doesn't include "while dragging" or outside AB, I think we can close this.

**Comment by DivyaPrabhakar** [comment]
I saw the same issues @chadrolfs was referring and a couple of new ones so I filed bugs for each of them and will close this one because it was an issue filed only about the X Y coordinates in the input fields, which is now fixed.
