### ISSUE TITLE
Consider adding additional export "settings" to adjust output quality

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2773]
Possible examples: high/low quality JPGs (using flite?), or high/low quality PNGs (8/24/32) (using pngquant?).

@placegraphichere: do you have any thoughts about this?
@mcilroyc: do you know what our status is w.r.t. flite and pngquant?
@chrisbank can you pretty please summarize the options exposed by Crema?

Thanks! Thanks! Thanks!

**Comment by chadrolfs** [comment]
@iwehrman is this just added sets of existing setting sets or is this actual additional UI?  M3 or push out?

**Comment by iwehrman** [comment]
This would be just additional entries in the "Settings" datalist:
![image](https://cloud.githubusercontent.com/assets/1075154/10561639/cd5311ac-74f7-11e5-8989-6f6912894da5.png)

I think if this is straightforward to do technically (and it seems like it should be) that this is important to add for M3.

**Comment by iwehrman** [comment]
Next step is to pick a few additional file type-settings pairs. Hopefully @placegraphichere can help with this.

**Comment by placegraphichere** [comment]
It'd probably be nice to offer some simple options, but since it's in a dropdown, we need to try and keep them tidy.

- PNG [this would be the default]
- PNG 8
- JPG 100%
- JPG 85%
- JPG 75%
- JPG 50%
- JPG 25%
- SVG
- PDF

I've included one setting at 85% since this is usually what I save high quality JPGs at, they tend to come out at a significantly smaller file size than 100% with very few artifacts.

I would not advocate for PNG24 at this point (m3), since in practical terms, it just means losing alpha, and adding a white color for the matte. Since we cannot yet change that matte color, it seems sort of odd it include it without much benefit for people. 

The same might apply to GIFs as well, when we allow more customization of the settings, then we may want to include it (ie 256, 128 colors etc). They can use PNG8 for that purpose, or we can drop PNG8 and use GIF. Either way, one 8bit option until more customization can occur.

**Comment by iwehrman** [comment]
Great, thanks @placegraphichere. Bouncing this to @mcilroyc.

**Comment by placegraphichere** [comment]
@mcilroyc I might suggest something like this for suffix on different file types/quality on the same export. It'd be great not to add them *unless* there are multiple files for say jpg or png with everything else matching. But I get the need to perhaps always do it.

PNG - Suffix `none` example `filename@XX.png`
PNG 8 - Suffix `-8` example: `filename@XX-8.png`
JPG 100% - Suffix `none` example: `filename@XX.jpg`
JPG 85% - Suffix `-85` example: `filename@XX-85.jpg`
JPG 75% - Suffix `-75` example: `filename@XX-75.jpg`
JPG 50% - Suffix `-50` example: `filename@XX-50.jpg`
JPG 25% - Suffix `-25` example: `filename@XX-25.jpg`
SVG - Suffix `none` example: `filename.svg`
PDF - Suffix `none` example: `filename.pdf`

**Comment by mcilroyc** [comment]
@placegraphichere yes, it would increase the complexity quite a bit to determine suffix based on the existence of other assets.  But we can definitely omit the quality portion of the suffix for PNG32 and JPG100.  See #3055

**Comment by iwehrman** [comment]
Fixed by #3055.
