### ISSUE TITLE
No user feedback when attempting to edit unsupported files with long names

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2842]
Open a 3D doc via double-clicking on a 3D asset in CC Library

Result: long name truncates and user has no idea the file is unsupported.

![screen shot 2015-10-06 at 4 18 34 pm](https://cloud.githubusercontent.com/assets/8442631/10325445/27126fe0-6c46-11e5-9fa6-4eb94da95fbe.png)

**Comment by chadrolfs** [comment]
related to #2547

**Comment by shaoshing** [comment]
We show an exclamation after the filename for unsupported documents. Guess it got truncated due to the long file name. Also, shall we make the mark more noticeable for the user?

<img width="423" alt="screen shot 2015-10-06 at 4 23 23 pm" src="https://cloud.githubusercontent.com/assets/118264/10325500/b7198e02-6c46-11e5-930a-366104dd159c.png">

**Comment by chadrolfs** [comment]
That would be great!

**Comment by iwehrman** [comment]
The exclamation mark used to be red, and I think it still should be. Maybe we should just move it to the left of the title? Where the "dirty" marker is?

**Comment by iwehrman** [comment]
@DivyaPrabhakar: Make the exclamation mark (i.e., the "unsupported file warning marker") red and move it to the left of the title.
