### ISSUE TITLE
CC Lib: content fails to download updated version; cache validation needed

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2863]
This asset is actually empty but cache on my machine still returns path successfully but fails when attempting to place or open to edit.

need a way to validate cache using the api.

![screen shot 2015-10-07 at 3 31 09 pm](https://cloud.githubusercontent.com/assets/8442631/10353124/be58bb80-6d08-11e5-9860-9be024247d92.png)

**Comment by shaoshing** [comment]
This is a problem caused by DS and the CC Libraries API. Let me explain and why it won't happen anymore:

Where are the empty asset came from:

1. at the initial development of the open-for-edit feature, we accidentally sent the wrong file path when updating graphic's content.
2. CC libraries accepted the wrong path anyway without validation and result in an empty graphic
3. the graphic was synced to other machines and they failed to generate a new preview out of nothing, so they just kept using the cached rendition.

As of now, we have a more robust open-for-edit feature, so step 1 is unlikely to happen. Even if we did (for example, the temp file is deleted manually while DS is updating it to the graphic), the new CC Libraries API won't perform the update, which prevent step 2 and 3 from happening (I verfieid this by sending a wrong path to the API deliberately).

You can force update of your local rendition caches to fix it in your machine:

1 `open ~/Library/Application\ Support/Adobe/Creative\ Cloud\ Libraries/LIBS`
2 delete the `LIBS` and `PHXS` folders
3 open ActivityMonitor, kill the `CCLibrary` process. it should restart shortly and re-download your libraries
4 view the library again and you should see the correct preview.
