### ISSUE TITLE
Undo after changing transform fields with negative values doesn't update correctly

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3154]
new doc
create 2 different sized Rects and select them both
enter W transform field, enter a negative number (-50), hit enter
Result: min value for each rect is set (0.1) but W field shows mixed state ( -- )
Repeat last step for H field
Result: now that field shows what you'd expect 0.1
cmd/ctrl + z undo (repeat)
Result: canvas updates but field remains 0.1
undo eventually results in 
`Transfer from history.decrementHistory to layers.resetLayerVisibility failed: Error: Photoshop returned an error when playing command number: 3 Photoshop code: 24946 Photoshop message: error: 24946 message: base element not found`

**Comment by chadrolfs** [comment]
![undo-xform](https://cloud.githubusercontent.com/assets/8442631/10798775/73666956-7d66-11e5-82b5-7fbeba2253de.gif)

**Comment by chadrolfs** [comment]
related to #3151

**Comment by chadrolfs** [comment]
![screen shot 2015-10-28 at 11 28 26 am](https://cloud.githubusercontent.com/assets/8442631/10798842/d1fe4556-7d66-11e5-95a4-4969963884af.png)

**Comment by mcilroyc** [comment]
Ok.  good news and bad news.  
bad: this is actually two separate bugs
good: I can narrow down the worse of the two bugs, and they can be treated separately, I think.  That is, the undo related bug has no relation to whether or not the number input shows a mixed state after entering a negative value:

repro:
start in the same way @chadrolfs described.  new doc, two rects, select both.  then...
- click into `W` field, input -50, hit *enter*
- (while still focused in input) cmd-Z
- Note in the console that it immediately enqueues both setSize and undo actions.  This is the root of the error that will follow if you undo again

My hunch is that, because this happens with W but not H, it may have to do with `_handleWidthKeyDown` in Size.jsx (unsubstantiated)

The separate bug with mixed states has to do with rounding, but I haven't investigated further
![rounding bounds](http://cl.ly/image/2k032m15053Q/Image%202015-10-28%20at%202.36.24%20PM.png)

I will say that I think these are both deferrable bugs given the edge behavior required to trigger them.

cc @iwehrman since you pinged me on slack about this.

**Comment by iwehrman** [comment]
Also note that the controller reset seems to handle this failure as gracefully as possible.

**Comment by chadrolfs** [comment]
Simple steps to hit error:
cmd/ctrl + n
r for Rect tool, draw out a rect
click in H transformation field, and put a minus in front of the number (ex. -128), hit enter
cmd/ctrl + n (x3)

**Comment by chadrolfs** [comment]
related to #3153
