### ISSUE TITLE
Chromium 47 SVG animation deprecation warning

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3217]
In Chromium 47, we get the following warning triggered by react-with-addons.js:20843:
```SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.```
~~Are we actually using SVG animations anywhere? It's possible that this warning will go away if we upgrade to React 0.14.~~

**Comment by designedbyscience** [comment]
I think we are for the loader

**Comment by iwehrman** [comment]
Sure enough: https://github.com/adobe-photoshop/spaces-design/blob/2a5dd74d5d414563efae4b9b075e5beeddd24bd1/src/img/ico-loader.svg?short_path=d608a50#L5-L12

**Comment by placegraphichere** [comment]
assigning to me

**Comment by placegraphichere** [comment]
This issue is a lot of fun. Seems that I can easily embed CSS into the SVG that will do the same animation. Problem is we do the `<use>` thing in order to place svg. The embedded CSS animation gets cut when you do that for some reason. Example of that will work in preview/browser, but not in `<svg><use>` that we have in Design Space:

---

`<svg version="1.1" id="loader" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="100%" height="100%" viewBox="0 0 16 16" xml:space="preserve">
    <style type="text/css">    
        #c1 {
            -webkit-animation: opacityLoop 1s infinite ease-in-out;
            -webkit-animation-delay: 0s;
            animation: opacityLoop 1s infinite ease-in-out;
            animation-delay: 0s;
        }
        #c2 {
            -webkit-animation: opacityLoop 1s infinite ease-in-out;
            -webkit-animation-delay: .1666s;
        }
        #c3 {
            -webkit-animation: opacityLoop 1s infinite ease-in-out;
            -webkit-animation-delay: .3333s;
        }
        #c4 {
            -webkit-animation: opacityLoop 1s infinite ease-in-out;
            -webkit-animation-delay: .4999s;
        }
        #c5 {
            -webkit-animation: opacityLoop 1s infinite ease-in-out;
            -webkit-animation-delay: .6666s;
        }
        #c6 {
            -webkit-animation: opacityLoop 1s infinite ease-in-out;
            -webkit-animation-delay: .8333s;
        }
        @-webkit-keyframes opacityLoop {
            0%   { opacity: 0; }
            50%   { opacity: 1; }
            100% { opacity: 0; }
        }
        @keyframes opacityLoop {
            from   { opacity: 0; }
            to   { opacity: 1; }
        }
    </style>
    <g transform="scale(.5625)">
        <circle cx="9" cy="7" r="3" id="c1">
        </circle>
        <circle  cx="17" cy="7" r="3" id="c2" opacity=".1666">
        </circle>
        <circle  cx="21" cy="13.5" r="3" id="c3" opacity=".3333">
        </circle>
        <circle  cx="17" cy="20" r="3" id="c4" opacity=".4999">
        </circle>
        <circle  cx="9" cy="20" r="3" id="c5" opacity=".6666">
        </circle>
        <circle  cx="5" cy="13.5" r="3" id="c6" opacity=".8333">
        </circle>
    </g>
</svg>`

---

I don't think CSS within our LESS is an alternative, since deep targeting is probably not possible.

I'm looking into some other ideas. Seems odd we wouldn't be able to animate some SVG here and there. @designedbyscience have any ideas?

**Comment by placegraphichere** [comment]
Here's a quick look at the `use` element with the CSS stripped out:
<img width="908" alt="screen shot 2015-11-22 at 11 38 45 pm" src="https://cloud.githubusercontent.com/assets/3229167/11330523/43717b94-9172-11e5-9642-150083eed844.png">

**Comment by iwehrman** [comment]
Fixed by #3405.
