### ISSUE TITLE
Guide policies misaligned

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3270]
On a 5k retina iMac with `font-size: 62.5%`, the guide policy areas are consistently misaligned:
![image](https://cloud.githubusercontent.com/assets/1075154/11253032/20afbe4a-8dee-11e5-9d66-abca4899c571.png)

**Comment by volfied** [comment]
hey @iwehrman can you test this to see whether the scroll changes outside those lines?

**Comment by iwehrman** [comment]
I do know that the cursor changes to an unadorned black arrow when it's in the policy area but NOT over the guide itself:

![img](https://s3.amazonaws.com/f.cl.ly/items/0O2g0i1w1f0w2t1l2X1r/Screen%20Recording%202016-01-11%20at%2003.04%20PM.gif?v=71844c61)

If I click and drag in that area, the drag fails silently.

**Comment by iwehrman** [comment]
It's better, but it's still not centered: 
![image](https://cloud.githubusercontent.com/assets/1075154/12339168/6357b8c2-bac8-11e5-8c88-eb3187143e3d.png)

It would be really nice to know why this is so far off...

**Comment by iwehrman** [comment]
Image above is retina; here's non-retina:
![image](https://cloud.githubusercontent.com/assets/1075154/12339206/9e0f0f88-bac8-11e5-8fa5-32ee508ba07a.png)

**Comment by volfied** [comment]
@iwehrman I agree with you that policies are not symmetric around the guide, but these areas are defined in PS and I'm matching them 1-to-1. If I enlarge the policy on the horizontal bottom / vertical right, we start sending PS move drag operations instead of guide drag. If I shrink it on the other side, we lose area of guide that's draggable, where cursor changes to guide move cursor but clicks deselect (since we get the mouse event).

So I'm trying to say this is a non-problem at this point, and only way to make it symmetric is to go into PS and change the guide drag zones there.

**Comment by iwehrman** [comment]
OK, then I'm just going to close this issue and try not to look at those guide zones any longer :stuck_out_tongue_closed_eyes:
