### ISSUE TITLE
Mask Mode with multiple layers selected does not work

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#3430]
- select an image layer and shape layer
- enter Mask Mode
- HUD will show and you can preview the results for the image layer
- Results in path showing that is not actually a mask, unclear what it is
![screen shot 2015-12-11 at 2 28 48 pm](https://cloud.githubusercontent.com/assets/3229167/11754824/8ad5673e-a013-11e5-8ada-9b77e4701b03.png)
![screen shot 2015-12-11 at 2 29 22 pm](https://cloud.githubusercontent.com/assets/3229167/11754829/998c33de-a013-11e5-8584-559e1a8099c5.png)

**Comment by mcilroyc** [comment]
@pineapplespatula after merging your PR, I get a new error.  (note that your unmerged branch seemed to work fine).

two selected layers: 
![ss](http://cl.ly/0x1E2k0j3e0m/Image%202016-01-07%20at%205.07.56%20PM.png)

console (press 'm' and click rectangle tool in HUD) http://cl.ly/3l2k3F0q1w1K

**Comment by mcilroyc** [comment]
Ok.  false alarm on that.  But.. phase two of my concern:   I think the multi-layer-selected case is still weird if the "first" layer is the shape layer.  It works fine if the layers look as my screenshot above, but if they order is reversed, then hitting "m" has no effect.  I'll toss this to @ktaki to get his take on the completion of this bug.  If @pineapplespatula feels that my concern is addressed elsewhere, or otherwise invalid, speak up.

**Comment by ktaki** [comment]
HUD is not shown, but you can draw a vector path with a shape tool. The result is a path drawn but does not create a mask as it was shown in the first description above. I think the vector mask icon and 'm' shortcut key should be disabled if multiple layers are selected.

**Comment by ktaki** [comment]
Retested the latest master branch. A mask is created when a layer and a shape layer are selected and hit m or Cmd-m regardless of the order of layers selected. If more than two layers are selected, the menu and icon on the doc bar are dimmed. Closing this as fixed.
