### ISSUE TITLE
Weird auto-complete behavior in search UI after failed query

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3529]
![img](https://s3.amazonaws.com/f.cl.ly/items/0w02000p0s1s3f1d1F0Z/Screen%20Recording%202016-01-14%20at%2010.56%20AM.gif?v=c18bdc86)

1. Open search UI
2. Type failed query, like "123" and press enter. The search UI is active but collapsed.
3. Type the first letter from one of the filters, like "o".

Result: the value of the search `TextInput` has jumped all the way to `"Open Documents"`.
Expected behavior: Only "o" should be in the `TextInput`, though it may well be the case that "Open Documents" is the first filtered result. In any case, it should behave exactly like it does if you type "o" the first time you open the search UI.

**Comment by DivyaPrabhakar** [comment]
@iwehrman Within #3479, I have made changes to the search bar as such -- If you type in an input with no results and press "Enter" or click on "No results", nothing with change in with the state of the search bar. This is different than before because it used to collapse the datalist of the search bar and now it does not. With this change, this issue ceases to exist. This is what it looks like if the changes within #3479 get merged (Note: The pause after my typing "1234" is me pressing "Enter" and as you can see, nothing happens to the state of the search bar) :

![](https://www.dropbox.com/s/5s21yv436dzp6iz/new%20search.gif?raw=1)

**Comment by DivyaPrabhakar** [comment]
Solved by #3479

**Comment by iwehrman** [comment]
@chadrolfs: can you verify this?

@DivyaPrabhakar: usually the person who opened the bug should verify it, or hand it off to QE for an impartial evaluation.
