### ISSUE TITLE
Closing files rapidly in succession will cause an error

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3678]
Action documents.close failed: TypeError: Cannot read property 'id' of null

The error can be seen closing large documents in succession by repeated Cmd/Ctrl-w, but easiest method for reproducing this error is the following.

1. Create two new documents by Cmd/Ctrl-n
2. Closing the two files by keep pressing Cmd/Ctrl-w

![screen shot 2016-02-05 at 11 05 40 am](https://cloud.githubusercontent.com/assets/2029597/12859260/dc05be20-cc09-11e5-93d4-abbde35dca34.png)

Note: A similar issue was reported and fixed in the issue #1813.

**Comment by chadrolfs** [comment]
I ran into this once yesterday but cnr on subsequent attempts.  Thanks for tracking this down.

**Comment by iwehrman** [comment]
I can repro. The problem is that the action assumes that a valid document model exists because the menu command is supposed to be disabled when that isn't the case. But the menu is not rebuilt for a few hundred milliseconds after the models are updated so that updates can be grouped, thus reducing unnecessary work. As a result, the `File > Close` command is enabled when it shouldn't be after the last document is closed, and so the user is allowed to execute a `documents.close` action in a state that violates that action's precondition. Simple fix coming right up...

**Comment by volfied** [comment]
FBNC to @ktaki

**Comment by ktaki** [comment]
Verified the fix.
