### ISSUE TITLE
Opening large documents in one open command may cause history warnings 

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3694]
... when opened doc was selected in doc bar. 
[History] Could not amend history, document history not found: 2424

(Related to the issue #3679 just fixed.)

Method:
0. Reset DS
1. Locate Vermilion doc and create a copy of it. (i.e., two Vermilions)
2. Cmd/Ctrl-o.
3. Select the original Vermilion doc and its copy at the same time.
4. Click Open.
5. After the docs are opened, select the first doc on the doc title bar.
(If do not repro, try with three or four duplicated Vermilion docs.)

![screen shot 2016-02-09 at 3 39 07 pm](https://cloud.githubusercontent.com/assets/2029597/12934430/4b0ef372-cf43-11e5-901b-d0eeaca0b3ae.png)

It seems no bad thing happening after the warning. Could this be just ignored?

**Comment by ktaki** [comment]
@mcilroyc: The warning still can be seen, but this time only one line instead of two lines.

![screen shot 2016-02-10 at 5 09 53 pm](https://cloud.githubusercontent.com/assets/2029597/12967184/4a8e2036-d019-11e5-807d-43b4f7ecfbb1.png)

**Comment by mcilroyc** [comment]
Yes @ktaki.  I am aware of the cause, but I'm not sure it is worth "fixing".  You might even notice *two* in a row.  I am reasonably certain that these limited warnings can now be safely ignored.  If you see a "[History] Initializing history..." log shortly thereafter, that indicates that this was just a brief race condition that has been neutralized :zap:.  There is a little more info in my rambling description of the PR #3695.  I recommend we close this bug because I think the warnings are now "within tolerance".

**Comment by ktaki** [comment]
OK. I agree. Closing.
