### ISSUE TITLE
Up/down arrow keys skip a line in the search dialog

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3707]
Traversing search dialog with up and down arrow keys skips a line.

![screen recording 2016-02-12 at 03 59 pm](https://cloud.githubusercontent.com/assets/2029597/13023896/750832e0-d1a2-11e5-9f32-0f2048325e81.gif)

**Comment by ktaki** [comment]
Apparently, this is Mac only.

**Comment by iwehrman** [comment]
I'm guessing this has to do with @jfitz-adobe's recent fix to ensure that keydown events were being correctly emitted on Mac. I believe @DivyaPrabhakar's current work should address this, so tentatively assigning to her.

**Comment by DivyaPrabhakar** [comment]
I am seeing this too and it occurred after @jfitz-adobe's change, so I agree, I think they are related. The other side effect is that when you type in the search bar and then backspace, it deletes two characters at a time.

**Comment by iwehrman** [comment]
Actually all `keydown` events are being duplicated on Mac at least. You can see this by arrowing left/right in a `TextInput` and watching the cursor move two steps instead of one. This is the result of a recent change by @jfitz-adobe, which has been rolled back by @volfied in CL 1063621. Hence, FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
