### ISSUE TITLE
New text layer always defaults to Myriad Pro Regular 16 px

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3769]
It does not inherit the settings of previously created text layer.

**Comment by iwehrman** [comment]
For me it _always_ seems to inherit the settings from the last layer I selected, even if no layers are currently selected, in which case it _should_ be Myriad Pro 16.

**Comment by shaoshing** [comment]
After some searching, I don't think we have the inherited type tool config implemented since the beginning, so this may be not a regression (unless the update of type tool config is managed in the PS side).

This is the commit that set the default type tool config on May last year https://github.com/adobe-photoshop/spaces-design/commit/3ea8d7f10da4866b53972e20e9e79eb409a079b8#diff-420547d8a9b5ced304c971dc662df535R37, and we've been using this setting since then.

**Comment by iwehrman** [comment]
I just did the same exploration and came to a similar conclusion, but I think that previous the assumption is that this was supposed to be the default behavior when a layer is selected. So, maybe standard Photoshop has a regression here?

**Comment by iwehrman** [comment]
@ktaki I can't repro your original bug. I think I still see that the settings from the selected layer are inherited. The behavior doesn't seem correct in case _no_ layers are selected (it uses the last selected layer's properties instead of Myriad Pro 16). But that doesn't seem like a ship blocker to me. What do you think?

**Comment by shaoshing** [comment]
@iwehrman @ktaki I confirm that this is a regression in the core side. I tried it in `pg dev 997` (lucky that I always keep the older versions :P) and the new text layers are inheriting the type configs.

**Comment by chadrolfs** [comment]
BTW, all the old sprint builds are in my transfer folder if anyone ever needs them.

**Comment by ktaki** [comment]
@iwehrman: The behavior you are describing is the original behavior up tp Ps 16.1.2. It changed to what I reported here sometime in the beginning of February. @shaoshing: Are you able to reproduce this? Are you saying the behavior reported here is correct according to the code you inspected? @chadrolfs: Can you try this also and let me know? Thanks!

**Comment by ktaki** [comment]
@shaoshing: Can you confirm you have reproduced this and this is a Ps Core bug? Then I will open a JIRA bug. Assign back to me.

**Comment by shaoshing** [comment]
@ktaki yes I confirm this is a core bug, since DS never implement such feature, and type tool does inherit the last config in `pg ddev 997`

**Comment by ktaki** [comment]
Opened https://jira.corp.adobe.com/browse/PS-1718

**Comment by ktaki** [comment]
This issue has been resolved by Ps Core fix.
