### ISSUE TITLE
Each click on color picker causes re-initializing of history in mixed appearance panel

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3801]
1. Create a text layer and a shape layer. 
2. Select both layers in the layers panel.
3. Open color picker in the appearance panel.
4. Click on it to change the color.

RESULT: Each click will cause a warning in console.

[History] Re-initializing history because photoshop thinks the current state is 11 of 12, while our model says 12 of 13
[History] Initializing history with 12 states

![screen shot 2016-03-11 at 1 50 05 pm](https://cloud.githubusercontent.com/assets/2029597/13716498/46a5521c-e790-11e5-800a-d5e0d79092ff.png)

Ref: #3465, #3662.

**Comment by mcilroyc** [comment]
It seems that the related feature of using the sampler to set the color of a combo text+shape selection is also broken in the same way, and has been for some time (or, always?).  So, it seems like this is not a direct result of #3662.

**Comment by mcilroyc** [comment]
I recommend this be deferred.  A fix would be risky.

some more info: when simultaneously setting the color of both a shape and text layer, two sub-actions are called: `shapeActions.setFillColor` and `typeActions.setColor`.  Each of these causes a DS history state to be created.  But, because they are played in PS as a single `transaction`, only one history state is created in PS.  This mismatch causes DS to reset its history state, which causes a performance hit during subsequent undo.

As I mentioned previously, it is not clear if this ever worked (for library sampling) or if it is a regression.

**Comment by ktaki** [comment]
Yes, that was something I suspected also. @DivyaPrabhakar: Do you mind if I close this?

**Comment by DivyaPrabhakar** [comment]
@ktaki Not a problem with me :) Thanks @mcilroyc for finding the problem.

**Comment by ktaki** [comment]
Closing the issue.
